define ->
  class Constants
    @REPLACEMENT_ATTRIBUTE: 'kmcs-r'
    @DISPLACEMENT_ATTRIBUTE: 'kmcs-d'
    @ANNOTATION_ATTRIBUTE: 'kmcs-a'
    @ACTIVE_ATTRIBUTE: 'kmcs-c'
    @PROPERTY: 'kmcs'
    @STATUS_ELEMENT_ID: 'kmcs-status'
    @DEFAULT_OPACITY: 0.1
